### ISSUE TITLE
Frantic creation issues

### ISSUE THREAD

**Issue by Techhead0** [Nubuscu/panic-pwa#2]
Frantic Heroes do not quite obey character creation rules:
- Rules dictate that all 3 styles must be from different archetypes. Instead the app allows you choose multiple styles from the same.
- Rules dictate that the 2 archetype abilities must match your styles, but the third archetype ability can be from any archetype. Instead the app forces the third style to be from one of the three archetypes.

**Comment by Nubuscu** [comment]
Hi, thanks for raising this! I've been a bit snowed under but I'll try to have a look at it shortly.

As a workaround for your second point, you should be able to select a different archetype, choose the style you want, then change the archetype back
